name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
jobs:
  python:
    strategy:
      fail-fast: false
      matrix:
        python: ['3.7', '3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: sudo apt-get install -y libsystemd-dev
    - name: Install pystemd
      run: pip install -e '.[t]'
    - name: Run unit tests
      run: pytest --cov=pystemd tests

  formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run black
      uses: psf/black@stable
    - name: Run isort
      uses: isort/isort-action@v1


  typing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: install mypy
      run:  pip install mypy types-psutil
    - name: run mypy
      run: mypy
